### ISSUE TITLE
English-Hindi Tokenization for the baseline model

### ISSUE THREAD

**Issue by sweta20** [amazon-research/contrastive-controlled-mt#3]
For En-Hi, the provided baseline model generates:
1. क ् या आपको लगता है कि उसकी गोलीबारी उचित थी क ् योंकि उसने पहले माफ ़ ी मांगी थी? 

instead of 

2. क्या आपको लगता है कि उनकी गोलीबारी जायज थी क्योंकि उन्होंने पहले माफी मांग ली थी? 

Is there a correct way to detokenize 1 to generate 2?
Also, what was the pre-processing used when training the baseline models?

**Comment by erip** [comment]
It looks like it's related to [this bug](https://github.com/alvations/sacremoses/issues/42) in sacremoses. It seems like it's [been fixed](https://github.com/alvations/sacremoses/pull/103), but perhaps we need to test from the main branch.

**Comment by bhsu22** [comment]
We've released an updated baseline en-hi model trained using the updated sacremoses tokenizers. You can find the model in our releases [here](https://github.com/amazon-research/contrastive-controlled-mt/releases/tag/v1.1.1).
